version: '3'

services: 
  redis:
    image: cassandra:3
    container_name: "cassandra"
    restart: always
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
    networks:
      - "cqlnet"

networks: 
  cqlnet: 
    driver: bridge